AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for deploying Vibe-beats to S3 + CloudFront'

Parameters:
  DomainName:
    Type: String
    Description: Domain name for CloudFront distribution (optional)
    Default: ''
  
  BucketName:
    Type: String
    Description: S3 bucket name for hosting
    Default: vibe-beats-app

Resources:
  # S3 Bucket for static content
  AppBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${BucketName}-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Application
          Value: VibeBeatsSPA

  # S3 Bucket Policy for CloudFront access
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref AppBucket
      PolicyText:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: 's3:GetObject'
            Resource: !Sub '${AppBucket.Arn}/*'
            Condition:
              StringEquals:
                'AWS:SourceArn': !Sub 'arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}'

  # CloudFront Distribution
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt AppBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${OriginAccessIdentity}'
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          DefaultTTL: 300
          MaxTTL: 3600
        CacheBehaviors:
          # Cache static assets for longer
          - PathPattern: '/assets/*'
            AllowedMethods:
              - GET
              - HEAD
            CachedMethods:
              - GET
              - HEAD
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: https-only
            ForwardedValues:
              QueryString: false
              Cookies:
                Forward: none
            DefaultTTL: 86400
            MaxTTL: 31536000
        CustomErrorResponses:
          # SPA routing: redirect 404s to index.html
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 300
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 300
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
      Tags:
        - Key: Application
          Value: VibeBeatsSPA

  # Origin Access Identity for CloudFront
  OriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub 'OAI for ${AWS::StackName}'

Outputs:
  S3BucketName:
    Description: S3 bucket name for uploading build files
    Value: !Ref AppBucket
    Export:
      Name: !Sub '${AWS::StackName}-BucketName'
  
  CloudFrontURL:
    Description: CloudFront distribution URL
    Value: !GetAtt CloudFrontDistribution.DomainName
    Export:
      Name: !Sub '${AWS::StackName}-DistributionURL'
  
  CloudFrontDistributionId:
    Description: CloudFront distribution ID for invalidations
    Value: !Ref CloudFrontDistribution
    Export:
      Name: !Sub '${AWS::StackName}-DistributionId'
